experiment:
  project: "baselines"
  tag: "cifar10_res50_pretrainI21k"
  model_save: "/home/vmagent/app/data/model"
dataset:
  type: "cifar10"
  num_workers: 10
  path: "/home/vmagent/app/data/dataset"
  train_transform: "pretrain112"
  test_transform: "pretrain112"
model:
  type: "resnet50"
solver:
  batch_size: 128
  epochs: 200
  optimizer:
    type: "SGD"
    lr: 0.1
    weight_decay: 5e-4
    momentum: 0.9
  scheduler:
    type: "CosineAnnealinglr"
    T_max: 200
  early_stop:
    flag: False
