EXPERIMENT:
  PROJECT: "baselines"
  TAG: "cifar100_res18"
DATASET:
  TYPE: "cifar100"
  PATH: "/home/vmagent/app/dataset/dataset/cifar"
MODEL:
  TYPE: "resnet18_v2"
FINETUNE:
  TYPE: "Basic"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  EARLY_STOP:
    FLAG: False