EXPERIMENT:
  PROJECT: "adapter"
  TAG: "usps_vs_mnist_CDAN"
  STRATEGY: "OnlyDomainAdaptionStrategy"
  MODEL_SAVE: '../model/'
  LOSS:
    BACKBONE: 1.0
    ADAPTER: 1.0
DATASET:
  TYPE: "USPS_vs_MNIST"
  PATH: "../datasets/USPS_vs_MNIST"
  NUM_WORKERS: 1
SOURCE_DATASET:
  TYPE: "USPS_vs_MNIST"
  PATH: "../datasets/USPS_vs_MNIST"
MODEL:
  TYPE: "LeNet"
ADAPTER:
  TYPE: "CDAN"
  FEATURE_SIZE: 500
  FEATURE_LAYER_NAME: "fc_layers_2"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 2
  LR: 0.002
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"