uid_voc: /home/vmagent/app/dataset/amazon_reviews_distributed/uid_voc.pkl
mid_voc: /home/vmagent/app/dataset/amazon_reviews_distributed/mid_voc.pkl
cat_voc: /home/vmagent/app/dataset/amazon_reviews_distributed/cat_voc.pkl
