EXPERIMENT:
  PROJECT: "distiller"
  TAG: "cifar100_dkd_res50_res18"
  STRATEGY: "OnlyDistillationStrategy"
  LOSS:
    BACKBONE: 1.0
    DISTILLER: 1.0
DATASET:
  TYPE: "cifar100"
  PATH: "/home/vmagent/app/dataset/dataset/cifar"
MODEL:
  TYPE: "resnet18_v2"
DISTILLER:
  TYPE: "DKD"
  TEACHER: 
      TYPE: "resnet50_v2"
      PRETRAIN: "/home/vmagent/app/dataset/model/baselines/gpu/cifar100_res50/student_best"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  EARLY_STOP:
    FLAG: False